config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :stations
end
root 'places#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
has_many :stations, dependent: :destroy
validates :property_name, presence: true
validates :rent, presence: true
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :place
  validates :station_name, presence:  true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:property_name, :rent, :address, :building_age, :remarks)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :get_place
  before_action :set_station, only: %i[ show edit update destroy ]

  # GET /stations or /stations.json
  def index
    @stations = @place.stations
  end

  # GET /stations/1 or /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = @place.stations.build
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations or /stations.json
  def create
    @station = @place.stations.build(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to place_stations_url(@place), notice: "Station was successfully created." }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1 or /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to place_stations_url(@place), notice: "Station was successfully updated." }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1 or /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to place_stations_url(@place), notice: "Station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = @place.stations.find(params[:id])
    end

    def get_place
      @place=Place.find(params[:place_id])
    end
    # Only allow a list of trusted parameters through.
    def station_params
      params.require(:station).permit(:name_of_railway_line, :station_name, :how_many_mins_walk, :place_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property_name %>
    <%= form.text_field :property_name %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.number_field :rent %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :building_age %>
    <%= form.number_field :building_age %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Property name</th>
      <th>Rent</th>
      <th>Address</th>
      <th>Building age</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.property_name %></td>
        <td><%= place.rent %></td>
        <td><%= place.address %></td>
        <td><%= place.building_age %></td>
        <td><%= place.remarks %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Property List </h1>
<p>
  <strong>Property Name:</strong>
  <%= @place.property_name %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @place.rent %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Building Age:</strong>
  <%= @place.building_age %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @place.remarks %>
</p>

<h2>Nearest Railway Line <% @station %></h2>
<% for station in @place.stations %>


<p>
  <strong>Name of railway line:</strong>
  <%= station.name_of_railway_line %></p>

<p><strong>Station name:</strong>
  <%= station.station_name %></p>

<p><strong>How many mins walk:</strong>
  <%= station.how_many_mins_walk %></p>
 <% end %>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Add Station', place_stations_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/stations/_form.html.erb
<%= form_with(model: [@place, station], local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name_of_railway_line %>
    <%= form.text_field :name_of_railway_line %>
  </div>

  <div class="field">
    <%= form.label :station_name %>
    <%= form.text_field :station_name %>
  </div>

  <div class="field">
    <%= form.label :how_many_mins_walk %>
    <%= form.number_field :how_many_mins_walk %>
  </div>

  <div class="field">
    <%= form.label :place_id %>
    <%= form.text_field :place_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', [@place, @station] %> |
<%= link_to 'Back', place_stations_path(@place) %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name of railway line</th>
      <th>Station name</th>
      <th>How many mins walk</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name_of_railway_line %></td>
        <td><%= station.station_name %></td>
        <td><%= station.how_many_mins_walk %></td>
        <td><%= station.place.property_name %></td>
        <td><%= link_to 'Show Place', [@place] %></td>
        <td><%= link_to 'Edit Station', edit_place_station_url(@place, station) %></td>
        <td><%= link_to 'Destroy Station', [@place, station], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_place_station_path(@place) %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', place_stations_path(@place) %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property name:</strong>
  <%= @station.place.property_name %>
</p>

<p>
  <strong>Name of railway line:</strong>
  <%= @station.name_of_railway_line %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @station.station_name %>
</p>

<p>
  <strong>How many mins walk:</strong>
  <%= @station.how_many_mins_walk %>
</p>

<%= link_to 'Show Place', [@station] %> |
<%= link_to 'Edit', edit_place_station_url(@place, @station) %> |
<%= link_to 'Back', place_stations_path(@place) %>